GET http://localhost:305/api/book

###
GET http://localhost:305/api/book/1

###
POST http://localhost:305/api/book

###
PATCH http://localhost:305/api/book/2

###
DELETE http://localhost:305/api/book/3